title: Eva Bacas
author: Eva Bacas
email: ENB30@pitt.edu
description: > # this means to ignore newlines until "baseurl:"
  Linguistics undergrad at Pitt.
# social links
twitter_username: evabacas
github_username:  vnbcs

# show_excerpts: true # set to false to remove excerpts on the homepage

theme: theme: minimal-mistakes-jekyll
